client_proxies_per_replica: 4
c_val: 0
f_val: 1
tls_cipher_suite_list: ECDHE-ECDSA-AES256-GCM-SHA384
tls_certificates_folder_path: ./tls_certs
comm_to_use: tls
FEATURE_time_service: true
perf_enable: true
eth_enable: false
tee_enable: false
preexecution_enabled: true
concord-bft_communication_buffer_length: 16000000
concord-bft_max_external_message_size: 2000000
#concord-bft_max_reply_message_size: 16777216
#concord-bft_max_num_of_reserved_pages: 65536
concord-bft_max_reply_message_size: 16384
concord-bft_max_num_of_reserved_pages: 144
node__TEMPLATE:
  logger_config: /concord/config-public/log4cplus.properties
  genesis_block: /concord/config-public/genesis.json
  blockchain_db_path: /concord/rocksdbdata/
  time_pusher_period_ms: 1000
  concord-bft_enable_debug_statistics: true
node:
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source1
    replica:
      - replica_host: concord1
        replica_port: 3501
    client_proxy:
      - client_host: concord1
        client_port: 3502
      - client_host: concord1
        client_port: 3503
      - client_host: concord1
        client_port: 3504
      - client_host: concord1
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source2
    replica:
      - replica_host: concord2
        replica_port: 3501
    client_proxy:
      - client_host: concord2
        client_port: 3502
      - client_host: concord2
        client_port: 3503
      - client_host: concord2
        client_port: 3504
      - client_host: concord2
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source3
    replica:
      - replica_host: concord3
        replica_port: 3501
    client_proxy:
      - client_host: concord3
        client_port: 3502
      - client_host: concord3
        client_port: 3503
      - client_host: concord3
        client_port: 3504
      - client_host: concord3
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source4
    replica:
      - replica_host: concord4
        replica_port: 3501
    client_proxy:
      - client_host: concord4
        client_port: 3502
      - client_host: concord4
        client_port: 3503
      - client_host: concord4
        client_port: 3504
      - client_host: concord4
        client_port: 3505
