version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - 5458:5458
    expose:
      - 5458
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
    depends_on:
      - fluentd

  ethrpc1:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8545:8545
    volumes:
      - ./config-ethrpc1:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord1:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc
    depends_on:
      - fluentd

  concord2:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - 5459:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
    depends_on:
      - fluentd

  ethrpc2:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8546:8545
    volumes:
      - ./config-ethrpc2:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord2:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc
    depends_on:
      - fluentd

  concord3:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - 5460:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
    depends_on:
      - fluentd

  ethrpc3:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8547:8545
    volumes:
      - ./config-ethrpc3:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord3:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc
    depends_on:
      - fluentd

  concord4:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - 5461:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
    depends_on:
      - fluentd

  ethrpc4:
    image: "${ethrpc_repo}:${ethrpc_tag}"
    ports:
      - 8548:8545
    volumes:
      - ./config-ethrpc4:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord4:5458
      - --security.require-ssl=true
      - --server.ssl.key-store-type=PKCS12
      - --server.ssl.key-store=/config/keystore.p12
      - '--server.ssl.key-store-password=Ethrpc!23'
      - --server.ssl.key-alias=ethrpc
    depends_on:
      - fluentd

  ui:
    image: "${ui_repo}:${ui_tag}"
    extra_hosts:
      - helen:${helen_ip}
    ports:
      - 80:80
    volumes:
      - ./ui/app-config.json:/usr/share/nginx/html/static/app-config.json

  contract-compiler:
    image: "${contract_compiler_repo}:${contract_compiler_tag}"
    ports:
      - 3000:3000

  db-server:
    image: postgres:10.6
    ports:
      - 26257:26257
    environment:
      POSTGRES_USER: helen_admin
      POSTGRES_DB: helen
      POSTGRES_PASSWORD: VMware!23
    command: -p 26257
    volumes:
      - ./devdata/postgresql:/var/lib/postgresql/data

  reverse-proxy:
    image: athena-docker-local.artifactory.eng.vmware.com/reverse-proxy:0.1.2
    extra_hosts:
      - helen:${helen_ip}
    ports:
      - "443:443"
      - "8843:8843"
    volumes:
      - ./data/nginx/docker-compose.conf.d:/etc/nginx/conf.d

  fluentd:
    image: "${fluentd_repo}:${fluentd_tag}"
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
          - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      - LOG_DESTINATION=LOG_INTELLIGENCE
      - LINT_ENDPOINT_URL=https://data.mgmt.cloud.vmware.com/le-mans/v1/streams/ingestion-pipeline-stream
      - "LINT_AUTHORIZATION_BEARER=${LINT_AUTHORIZATION_BEARER}"
      - LOG_INSIGHT_HOST=10.78.20.10
      - LOG_INSIGHT_PORT=9000
      - LOG_INSIGHT_AGENT_ID=0
      - CONSORTIUM_ID=100
      - REPLICA_ID=1

  agent:
    image: "${persephone_agent_repo}:${persephone_agent_tag}"
    ports:
      - 50453:50453
