# Minimum docker deployment for vDAML.
# In contrast to the full deployment, it only contains 2 ledger api servers
# and a single postgres database cluster with 2 separate index databases on it.

version: '3'
services:
  # Note: Make sure that Concord's configuration files have `daml_enable` set
  concord1:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    depends_on:
      - daml_execution_engine1
    ports:
      - "50051:50051"
    expose:
      - 5458
      - 9891
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord2:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    depends_on:
      - daml_execution_engine2
    ports:
      - "50052:50051"
    expose:
      - 5458
      - 9891
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord3:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    depends_on:
      - daml_execution_engine3
    ports:
      - "50053:50051"
    expose:
      - 5458
      - 9891
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  concord4:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    depends_on:
      - daml_execution_engine4
    ports:
      - "50054:50051"
    expose:
      - 5458
      - 9891
      - 3501/udp
      - 3502/udp
      - 3503/udp
      - 3504/udp
      - 3505/udp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro

  daml_ledger_api1:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    environment:
      - INDEXDB_HOST=index_db
      - INDEXDB_PORT=5432
      - INDEXDB_USER=indexdb
      - REPLICAS=concord1:50051,concord2:50051,concord3:50051,concord4:50051
      - ENABLE_BATCHING=false
      - PARTICIPANT_ID=daml_ledger_api1
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    depends_on:
      - concord1
      - index_db
    expose:
      - 6865
      - 55001
    ports:
      - "6861:6865"

  daml_ledger_api2:
    image: "${daml_ledger_api_repo}:${daml_ledger_api_tag}"
    environment:
      - INDEXDB_HOST=index_db
      - INDEXDB_PORT=5432
      - INDEXDB_USER=indexdb
      - REPLICAS=concord2:50051,concord3:50051,concord4:50051,concord1:50051
      - ENABLE_BATCHING=false
      - PARTICIPANT_ID=daml_ledger_api2
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    depends_on:
      - concord2
      - index_db
    expose:
      - 6865
      - 55001
    ports:
      - "6862:6865"

  daml_execution_engine1:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    expose:
      - 55000
      - 55001
    ports:
      - "55001:55001" # metrics dashboard

  daml_execution_engine2:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    expose:
      - 55000
      - 55001
    ports:
      - "55002:55001" # metrics dashboard

  daml_execution_engine3:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    expose:
      - 55000
      - 55001
    ports:
      - "55003:55001" # metrics dashboard

  daml_execution_engine4:
    image: "${daml_execution_engine_repo}:${daml_execution_engine_tag}"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -Xmx4G
    expose:
      - 55000
      - 55001
    ports:
      - "55004:55001" # metrics dashboard

  index_db:
    image: "${daml_index_db_repo}:${daml_index_db_tag}"
    restart: always
    environment:
      - POSTGRES_USER=indexdb
      - POSTGRES_MULTIPLE_DATABASES=daml_ledger_api1,daml_ledger_api2
      - MAX_CONNECTIONS=300
      - BUFFER_SIZE=80MB
    volumes:
      - ./devdata/index_db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
