apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      imagePullSecrets:
        - name: bintray
      hostname: ui
      containers:
      - name: ui
        image: vmware-docker-blockchainsaas.bintray.io/vmwblockchain/ui:{{BUILDNUM}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        - name: ui-volume
          mountPath: /usr/share/nginx/html/static/app-config.json
          subPath: app-config.json
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx
          defaultMode: 0700
      - name: ui-volume
        configMap:
          name: uicontext
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ui